### ISSUE TITLE
Any way it import json files back to reminder app?

### ISSUE THREAD

**Issue by TopstarBluecoat** [Kylmakalle/apple-reminders-exporter#2]
Hallo and thanks a lot for providing a solution to export all reminders from the reminder app. I was looking for such a solution for a long time.

Is there any way to import these json files back to the reminders app? I'm looking for a way to bring the data back to the reminders app in case of losing them. At the moment I can only think of opening each and every json file and copy & paste the content to the reminders app, but there might be an easier way to do so.

**Comment by Kylmakalle** [comment]
> [Reminders are actually `.ics` files](https://github.com/Kylmakalle/apple-reminders-exporter#:~:text=Reminders%20are%20actually%20.ics%20files.)

`.ics` are Calendar events, I think it will be much easier in terms of importing them back (into both Reminders or any other compatible app). Unfortunately, some data loss may still happen and the rest of the approaches from Readme are focused on the export, not import. Consider this [CLI](https://github.com/keith/reminders-cli) if you need to go back and forth with your data.

**Comment by TopstarBluecoat** [comment]
Thank you for your feedback. Unfortunately, I do not know how to bring the JSON = .ics files back to the reminders app. I've googled for hours, but was not able to find any hint. I would therefore like to ask you if you could kindly give me a little tip on how to proceed. I've looked at the CLI, but struggled with the installation and how to build scripts that are doing the export and import. Thanks a lot in advance.

**Comment by Kylmakalle** [comment]
@TopstarBluecoat I don't know any easy ways to import reminders, but it's likely implemented in some other solutions linked in the end of the README
